// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZLDwFyU7_KrCasUZuoKCeg7tVWIfJN4',
    appId: '1:572523155936:web:caa6899c5bdf9669dc5b85',
    messagingSenderId: '572523155936',
    projectId: 'chat-app-83b33',
    authDomain: 'chat-app-83b33.firebaseapp.com',
    storageBucket: 'chat-app-83b33.firebasestorage.app',
    measurementId: 'G-HMBMFZ6H5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWp8BHVIOpi1HhEamq9ZVAVxkQCytxPZA',
    appId: '1:572523155936:android:390888e6b578c173dc5b85',
    messagingSenderId: '572523155936',
    projectId: 'chat-app-83b33',
    storageBucket: 'chat-app-83b33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhTPUo8iHcUvr2HHcnbNu5V7Kr-1gD7Fc',
    appId: '1:572523155936:ios:c1e853b456ebd09bdc5b85',
    messagingSenderId: '572523155936',
    projectId: 'chat-app-83b33',
    storageBucket: 'chat-app-83b33.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhTPUo8iHcUvr2HHcnbNu5V7Kr-1gD7Fc',
    appId: '1:572523155936:ios:c1e853b456ebd09bdc5b85',
    messagingSenderId: '572523155936',
    projectId: 'chat-app-83b33',
    storageBucket: 'chat-app-83b33.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEZLDwFyU7_KrCasUZuoKCeg7tVWIfJN4',
    appId: '1:572523155936:web:3406d4411066bbbddc5b85',
    messagingSenderId: '572523155936',
    projectId: 'chat-app-83b33',
    authDomain: 'chat-app-83b33.firebaseapp.com',
    storageBucket: 'chat-app-83b33.firebasestorage.app',
    measurementId: 'G-NJXV6R2959',
  );
}
